In [1]:
import pandas as pd
import numpy as np


file_path=r'C:\Users\rishi\OneDrive\Desktop\Python projects\amazon_india_2015.csv'

df = pd.read_csv(file_path)

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\4193443328.py:7: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [2]:
#df = df.drop("Unnamed: 0", axis=1)

df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,4.0,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,21947.26,0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

##Q1 order_date columns clean

In [3]:

df = pd.read_csv(file_path)

df['order_date']=pd.to_datetime(df['order_date'], format='mixed')



df.to_csv(file_path, index=False)

print(" order_date clean and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\3176102917.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

 order_date clean and file updated successfully.

In [4]:
df['order_date'].unique()

<DatetimeArray>
['2015-01-25 00:00:00', '2015-01-05 00:00:00', '2015-01-24 00:00:00',
 '2015-01-28 00:00:00', '2015-01-31 00:00:00', '2015-01-04 00:00:00',
 '2015-01-27 00:00:00', '2015-01-08 00:00:00', '2015-01-18 00:00:00',
 '2015-01-03 00:00:00',
 ...
 '2015-12-13 00:00:00', '2015-12-22 00:00:00', '2015-12-23 00:00:00',
 '2015-12-19 00:00:00', '2015-12-15 00:00:00', '2015-12-31 00:00:00',
 '2015-12-25 00:00:00', '2015-12-29 00:00:00', '2015-12-27 00:00:00',
 '2015-12-21 00:00:00']
Length: 365, dtype: datetime64[us]

##Q2 Original_price_inr

In [5]:
df = pd.read_csv(file_path)

df['original_price_inr'] = df['original_price_inr'].astype(str)

chars_to_remove = ['+', ',', '$', 'Rs', '₹', '-']

for item in chars_to_remove:
    df['original_price_inr'] = df['original_price_inr'].str.replace(item, '', regex=False)

df['original_price_inr'] = pd.to_numeric(df['original_price_inr'], errors='coerce')

df.to_csv(file_path, index=False)

print("original_price_inr cleaned successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\4265221720.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

original_price_inr cleaned successfully.

In [6]:
df['original_price_inr'].unique()

array([123614.29  ,  54731.86  ,  97644.25  ,  21947.26  , 131194.65  ,
        86987.64  ,  32169.01  ,  40264.16  ,  88664.85  ,  73967.02  ,
        72564.1   ,   2098.7555,  45363.47  ,  23075.71  , 114096.63  ,
        69584.33  ,  38884.19  ,  46234.09  ,  15065.01  , 164166.84  ,
        64917.57  ,  29534.7   ,  86477.53  ,  13721.42  , 118141.16  ,
        86591.57  ,  23264.31  ,  94029.64  ,  17206.23  ,  37013.54  ,
       130430.24  , 130723.61  ,  41408.67  ,  56337.89  ,  75380.48  ,
        23161.1   ,  46680.9   ,  43572.75  ,  19375.09  ,   3896.99  ,
        20006.12  ,  30990.65  ,  96543.62  ,  22683.69  , 102649.14  ,
       107387.37  ,  67444.91  ,  24762.02  ,  17790.72  ,  47979.    ,
        24448.87  , 102741.22  ,  51356.92  ,  33199.84  ,   9753.11  ,
        88872.68  ,  72369.63  , 126454.    ,  24762.    ,  78047.8   ,
        60643.25  , 145589.8   ,  21212.    ,  40438.41  ,  12984.58  ,
        39490.87  ,  40307.83  ,  62405.02  ,  11071.95  ,  82953.19  ,
        20323.89  , 173203.42  ,  46458.94  ,  95494.86  ,  35581.67  ,
        31102.54  ,   1904.691 ,  19871.97  ,   2117.2116,  25093.87  ,
        21211.5   ,  52280.35  ,  29350.42  , 169544.4   ,  19864.16  ,
        13495.03  ,  46234.    ,  76246.51  ,   5646.16  ,  24160.32  ,
        43767.4   ,  39010.09  , 173499.67  ,  28668.34  ,  23087.98  ,
        26317.1   ,  74885.61  ,  97905.92  ,  45182.31  ,  42790.64  ,
       114806.24  ,  20175.12  , 131421.21  ,  47978.89  ,  22779.49  ,
       136176.95  ,  23391.49  ,  39491.    ,  17869.25  ,  36351.    ,
        57182.39  ,  77250.03  , 185009.58  , 179795.49  , 132678.66  ,
       167952.46  , 130430.    ,  10481.43  ,  17869.    ,  11531.6   ,
        22684.    , 117289.33  ,   9429.82  , 109664.46  , 164828.19  ,
       180530.75  ,  21456.84  , 137590.    , 155958.9   ,  17718.71  ,
        17116.37  ,   1831.8573, 118740.51  , 150746.2   , 117289.    ,
       137589.7   ,  44830.4   ,  20321.71  ,  97906.    ,  29675.17  ,
       107387.    ,  20258.29  ,   1872.3201, 140946.79  ,  13440.84  ,
        45182.    ,   4483.04  ,  57182.    ,  36350.6   ,  37014.    ,
        44203.12  , 159742.47  , 140947.    ,  15228.53  ,  16406.11  ,
       131195.    ,  31103.    , 139307.76  , 169270.03  ,  88665.    ,
        17717.09  ,  77250.    , 158424.89  ,  14362.6   , 118141.    ,
        29675.    ,  86592.    ,   8978.5   ,  17791.    ,  13344.05  ,
       114806.    ,  13965.56  , 184704.89  ,  12171.1   ,  13790.62  ,
        20937.46  ,  20324.    , 139751.59  ,   2098.76  ,  39010.    ,
         1897.2448,  11648.02  , 162866.91  ,  33200.    ,  24449.    ,
         7720.51  ,   3795.01  ,  75380.    ,  28668.    ,  12757.3   ,
       148346.57  ,   1831.86  ,  78048.    ,  13921.72  ,  54732.    ,
       152015.02  , 151260.    ,   2374.84  ,  72370.    ,   1986.416 ,
         7236.963 ,  96544.    ,  11187.99  ,  11459.64  ,  44830.    ,
        51357.    , 123614.    ,   8647.753 ,  40264.    ,   3949.087 ,
        45363.    ,  46681.    ,  17719.    ,  40438.    ,  17174.29  ,
         5633.789 ,  20322.    ,  10481.    ,  60643.    ,  20937.    ,
         1897.24  ,  46459.    ,  74886.    ,  26317.    ,   8887.268 ,
        29535.    ,  64918.    ,   2316.11  ,  23391.    ,  21947.    ,
        32169.    ,  88873.    ,  52280.    , 118741.    ,  73967.    ,
        72564.    , 132679.    , 114097.    , 167952.    ,   2017.512 ,
       109664.    ,  20006.    ,  20175.    ,   2375.    ,  19872.    ,
        13344.    ,  42791.    ,   3558.167 ,  23748.4   ,  23076.    ,
         9430.    ,  23161.    ,  25094.    ,  19375.    ,  67445.    ,
        43573.    ,  17116.    ,  13721.    ,   9402.964 ,  40308.    ,
        38884.    ,  82953.    ,  20258.    ,  30991.    ,  13441.    ,
         3795.    , 162867.    ,   2307.571 ,  11072.    ,   6958.433 ,
        24160.    ,   6064.325 ,  21457.    ,  95495.    ,  62405.    ,
       185010.    ,  97644.    ,   1872.32  ,  86988.    ,  22779.    ,
        29350.    ,   1904.69  ,   2121.15  ,   8978.    ,   7256.41  ,
       155959.    , 152015.    ,  44203.    ,   4030.783 ,  40264.16  ,
       130724.    ,  43767.    ,  23088.    ,  56338.    ,  12645.4   ,
        69584.    ,  23264.    , 164828.    ,  19864.    ,  41409.    ,
       159742.    ,  76247.    , 136177.    ,  11532.    ,  12757.    ,
        11188.    ,   5646.    ,  94030.    ,   3897.    ,   2416.032 ,
       102649.    ,   2339.149 , 158425.    ,   2117.21  ,  17717.    ,
        14363.    ,  16927.003 , 134950.3   ,  35582.    ,   2268.369 ,
        15229.    , 139308.    ,  13495.    , 148347.    ,   8866.485 ,
         9753.    ,  13072.361 , 145590.    ,   7804.78  ,  11460.    ,
        15201.502 ,  86478.    ,   4043.841 ,  13791.    , 102741.    ,
         7721.    , 184705.    , 169270.    ,  10966.446 ,  13966.    ,
         2866.834 ,  13922.    ,   9654.362 ,  17174.    , 164167.    ,
         4376.74  , 150746.    , 139752.    ,   2967.517 , 179795.    ,
       180531.    ,   2194.726 ,  20987.555 ,   3635.06  ,   6491.757 ,
         4623.409 , 177187.1   ,   2277.949 ,   2093.746 ,  16406.    ,
         7488.561 ,   7538.048 ,   4279.064 ,  17206.    ,   8698.764 ,
       152285.3   ,   4668.09  ,   1987.197 ,  13975.159 ,  15595.89  ,
         2631.71  ,  12171.    ,   4645.894 ,  11648.    ,  11814.116 ,
        14558.98  ,   2032.389 ,   5135.692 ])

##Q3 customer_rating columns clean

In [7]:
df = pd.read_csv(file_path)

chars2_to_remove=['stars']
cols_to_clean2=['customer_rating']
for item in chars2_to_remove:
    for cols in cols_to_clean2:
        df[cols]=df[cols].astype(str).str.replace(item,'', regex=False)

df['customer_rating'] = df['customer_rating'].astype(str).str.split('/').str[0]

df.to_csv(file_path, index=False)

print(" customer_rating clean and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\3736996782.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

 customer_rating clean and file updated successfully.

##Q4 customer_city

In [8]:
df = pd.read_csv(file_path)

city_map = {
    'ahmedabad': 'Ahmedabad',
    'aligarh': 'Aligarh',
    'allahabad': 'Allahabad',
    'bangalore': 'Bengaluru',
    'banglore': 'Bengaluru',
    'bengalore': 'Bengaluru',
    'bengaluru': 'Bengaluru',
    'bhubaneswar': 'Bhubaneswar',
    'bombay': 'Mumbai',
    'calcutta': 'Kolkata',
    'chandigarh': 'Chandigarh',
    'chenai': 'Chennai',
    'chennai': 'Chennai',
    'coimbatore': 'Coimbatore',
    'customer_city': 'Unknown',
    'delhi': 'Delhi',
    'delhi ncr': 'Delhi',
    'new delhi': 'Delhi',
    'gorakhpur': 'Gorakhpur',
    'hyderabad': 'Hyderabad',
    'indore': 'Indore',
    'jaipur': 'Jaipur',
    'kanpur': 'Kanpur',
    'kochi': 'Kochi',
    'kolkata': 'Kolkata',
    'lucknow': 'Lucknow',
    'ludhiana': 'Ludhiana',
    'madras': 'Chennai',
    'meerut': 'Meerut',
    'moradabad': 'Moradabad',
    'mumba': 'Mumbai',
    'mumbai': 'Mumbai',
    'nagpur': 'Nagpur',
    'patna': 'Patna',
    'pune': 'Pune',
    'saharanpur': 'Saharanpur',
    'surat': 'Surat',
    'vadodara': 'Vadodara',
    'varanasi': 'Varanasi',
    'visakhapatnam': 'Visakhapatnam'
}

df['customer_city'] = df['customer_city'].str.lower().map(city_map)

df.to_csv(file_path, index=False)

print(" customer_city clean and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\810657689.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

 customer_city clean and file updated successfully.

##Q5 is_prime_member, is_prime_eligible, is_festival_sale

In [9]:
df['is_festival_sale'].unique()

array([ True, False])

In [10]:
df = pd.read_csv(file_path)

# Define a universal boolean cleaner
def clean_boolean(value):
    try:
        value = str(value).strip().lower()
        if value in ['true', 'yes', 'y', '1']:
            return True
        elif value in ['false', 'no', 'n', '0']:
            return False
        else:
            return False  # or use pd.NA if you want to preserve missing
    except:
        return False

# Apply to all relevant columns
boolean_columns = ['is_prime_member', 'is_prime_eligible', 'is_festival_sale']
for col in boolean_columns:
    df[col] = df[col].apply(clean_boolean)
    
df['is_prime_member']=df['is_prime_member'].astype(bool)
df['is_prime_eligible']=df['is_prime_eligible'].astype(bool)
df['is_festival_sale']=df['is_festival_sale'].astype(bool)
# Save the cleaned data back to the same file
df.to_csv(file_path, index=False)

print(" Boolean columns standardized to True/False and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\2298127848.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

 Boolean columns standardized to True/False and file updated successfully.

In [11]:
df['is_prime_eligible'].unique()

array([ True, False])

##Q6 categories

In [12]:
df['category'].unique()

<StringArray>
['Electronics']
Length: 1, dtype: str

In [13]:
# Q6: Standardize product categories

df = pd.read_csv(file_path)

# Normalize category names
df['category'] = df['category'].str.lower().str.strip()

# Define mapping for standardization
category_map = {
    'electronics': 'Electronics',
    'electronic': 'Electronics',
    'electronics & accessories': 'Electronics',
    'electronicss': 'Electronics'
}

# Apply mapping
df['category'] = df['category'].replace(category_map)

# Capitalize standardized names
df['category'] = df['category'].str.title()

# Overwrite the original file with cleaned data
df.to_csv(file_path, index=False)

print(" Category names standardized and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\1881120276.py:3: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

 Category names standardized and file updated successfully.

##Q7 delivery_days

In [14]:
df['delivery_days'].unique()

array([ 6,  4,  3,  5,  7,  0,  1,  2, 15])

In [15]:
df = pd.read_csv(file_path)

d_days={
   "Same Day":"0",
   "Express":"0",
    "1-2 days":"2",
    "-1":"1"
}

def clean_delivery_days(value):
    val = str(value).strip()
    return d_days.get(val, val)

df["delivery_days"] = df["delivery_days"].apply(clean_delivery_days)

df["delivery_days"]=df["delivery_days"].astype(int)


df.to_csv(file_path, index=False)

print(" delivery_days corrected and saved ")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\505917379.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

 delivery_days corrected and saved

In [16]:
df['delivery_days'].unique()

array([ 6,  4,  3,  5,  7,  0,  1,  2, 15])

##Q8 customer_id', 'product_id', 'order_date', 'final_amount_inr

In [17]:
df[df.duplicated('product_id')].shape

(32836, 34)

In [18]:
# Q8: Flag duplicates
import pandas as pd

# Load your dataset

df = pd.read_csv(file_path)

df[df.duplicated(subset=['customer_id', 'product_id', 'order_date', 'final_amount_inr'], keep=False)]
df=df.drop_duplicates(subset=['customer_id', 'product_id', 'order_date', 'final_amount_inr'],keep='first')


# Overwrite original file with cleaned data
df.to_csv(file_path, index=False)

print("✅ Flag duplicates corrected and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\3095654537.py:6: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Flag duplicates corrected and file updated successfully.

In [19]:
df[df.duplicated(subset=['customer_id', 'product_id', 'order_date', 'final_amount_inr'], keep=False)]

Empty DataFrame
Columns: [transaction_id, order_date, customer_id, product_id, product_name, category, subcategory, brand, original_price_inr, discount_percent, discounted_price_inr, quantity, subtotal_inr, delivery_charges, final_amount_inr, customer_city, customer_state, customer_tier, customer_spending_tier, customer_age_group, payment_method, delivery_days, delivery_type, is_prime_member, is_festival_sale, festival_name, customer_rating, return_status, order_month, order_year, order_quarter, product_weight_kg, is_prime_eligible, product_rating]
Index: []

[0 rows x 34 columns]

##Q9

In [20]:
df['original_price_inr'].unique()

array([123614.29  ,  54731.86  ,  97644.25  ,  21947.26  , 131194.65  ,
        86987.64  ,  32169.01  ,  40264.16  ,  88664.85  ,  73967.02  ,
        72564.1   ,   2098.7555,  45363.47  ,  23075.71  , 114096.63  ,
        69584.33  ,  38884.19  ,  46234.09  ,  15065.01  , 164166.84  ,
        64917.57  ,  29534.7   ,  86477.53  ,  13721.42  , 118141.16  ,
        86591.57  ,  23264.31  ,  94029.64  ,  17206.23  ,  37013.54  ,
       130430.24  , 130723.61  ,  41408.67  ,  56337.89  ,  75380.48  ,
        23161.1   ,  46680.9   ,  43572.75  ,  19375.09  ,   3896.99  ,
        20006.12  ,  30990.65  ,  96543.62  ,  22683.69  , 102649.14  ,
       107387.37  ,  67444.91  ,  24762.02  ,  17790.72  ,  47979.    ,
        24448.87  , 102741.22  ,  51356.92  ,  33199.84  ,   9753.11  ,
        88872.68  ,  72369.63  , 126454.    ,  24762.    ,  78047.8   ,
        60643.25  , 145589.8   ,  21212.    ,  40438.41  ,  12984.58  ,
        39490.87  ,  40307.83  ,  62405.02  ,  11071.95  ,  82953.19  ,
        20323.89  , 173203.42  ,  46458.94  ,  95494.86  ,  35581.67  ,
        31102.54  ,   1904.691 ,  19871.97  ,   2117.2116,  25093.87  ,
        21211.5   ,  52280.35  ,  29350.42  , 169544.4   ,  19864.16  ,
        13495.03  ,  46234.    ,  76246.51  ,   5646.16  ,  24160.32  ,
        43767.4   ,  39010.09  , 173499.67  ,  28668.34  ,  23087.98  ,
        26317.1   ,  74885.61  ,  97905.92  ,  45182.31  ,  42790.64  ,
       114806.24  ,  20175.12  , 131421.21  ,  47978.89  ,  22779.49  ,
       136176.95  ,  23391.49  ,  39491.    ,  17869.25  ,  36351.    ,
        57182.39  ,  77250.03  , 185009.58  , 179795.49  , 132678.66  ,
       167952.46  , 130430.    ,  10481.43  ,  17869.    ,  11531.6   ,
        22684.    , 117289.33  ,   9429.82  , 109664.46  , 164828.19  ,
       180530.75  ,  21456.84  , 137590.    , 155958.9   ,  17718.71  ,
        17116.37  ,   1831.8573, 118740.51  , 150746.2   , 117289.    ,
       137589.7   ,  44830.4   ,  20321.71  ,  97906.    ,  29675.17  ,
       107387.    ,  20258.29  ,   1872.3201, 140946.79  ,  13440.84  ,
        45182.    ,   4483.04  ,  57182.    ,  36350.6   ,  37014.    ,
        44203.12  , 159742.47  , 140947.    ,  15228.53  ,  16406.11  ,
       131195.    ,  31103.    , 139307.76  , 169270.03  ,  88665.    ,
        17717.09  ,  77250.    , 158424.89  ,  14362.6   , 118141.    ,
        29675.    ,  86592.    ,   8978.5   ,  17791.    ,  13344.05  ,
       114806.    ,  13965.56  , 184704.89  ,  12171.1   ,  13790.62  ,
        20937.46  ,  20324.    , 139751.59  ,   2098.76  ,  39010.    ,
         1897.2448,  11648.02  , 162866.91  ,  33200.    ,  24449.    ,
         7720.51  ,   3795.01  ,  75380.    ,  28668.    ,  12757.3   ,
       148346.57  ,   1831.86  ,  78048.    ,  13921.72  ,  54732.    ,
       152015.02  , 151260.    ,   2374.84  ,  72370.    ,   1986.416 ,
         7236.963 ,  96544.    ,  11187.99  ,  11459.64  ,  44830.    ,
        51357.    , 123614.    ,   8647.753 ,  40264.    ,   3949.087 ,
        45363.    ,  46681.    ,  17719.    ,  40438.    ,  17174.29  ,
         5633.789 ,  20322.    ,  10481.    ,  60643.    ,  20937.    ,
         1897.24  ,  46459.    ,  74886.    ,  26317.    ,   8887.268 ,
        29535.    ,  64918.    ,   2316.11  ,  23391.    ,  21947.    ,
        32169.    ,  88873.    ,  52280.    , 118741.    ,  73967.    ,
        72564.    , 132679.    , 114097.    , 167952.    ,   2017.512 ,
       109664.    ,  20006.    ,  20175.    ,   2375.    ,  19872.    ,
        13344.    ,  42791.    ,   3558.167 ,  23748.4   ,  23076.    ,
         9430.    ,  23161.    ,  25094.    ,  19375.    ,  67445.    ,
        43573.    ,  17116.    ,  13721.    ,   9402.964 ,  40308.    ,
        38884.    ,  82953.    ,  20258.    ,  30991.    ,  13441.    ,
         3795.    , 162867.    ,   2307.571 ,  11072.    ,   6958.433 ,
        24160.    ,   6064.325 ,  21457.    ,  95495.    ,  62405.    ,
       185010.    ,  97644.    ,   1872.32  ,  86988.    ,  22779.    ,
        29350.    ,   1904.69  ,   2121.15  ,   8978.    ,   7256.41  ,
       155959.    , 152015.    ,  44203.    ,   4030.783 ,  40264.16  ,
       130724.    ,  43767.    ,  23088.    ,  56338.    ,  12645.4   ,
        69584.    ,  23264.    , 164828.    ,  19864.    ,  41409.    ,
       159742.    ,  76247.    , 136177.    ,  11532.    ,  12757.    ,
        11188.    ,   5646.    ,  94030.    ,   3897.    ,   2416.032 ,
       102649.    ,   2339.149 , 158425.    ,   2117.21  ,  17717.    ,
        14363.    ,  16927.003 , 134950.3   ,  35582.    ,   2268.369 ,
        15229.    , 139308.    ,  13495.    , 148347.    ,   8866.485 ,
         9753.    ,  13072.361 , 145590.    ,   7804.78  ,  11460.    ,
        15201.502 ,  86478.    ,   4043.841 ,  13791.    , 102741.    ,
         7721.    , 184705.    , 169270.    ,  10966.446 ,  13966.    ,
         2866.834 ,  13922.    ,   9654.362 ,  17174.    , 164167.    ,
         4376.74  , 150746.    , 139752.    ,   2967.517 , 179795.    ,
       180531.    ,   2194.726 ,  20987.555 ,   3635.06  ,   6491.757 ,
         4623.409 , 177187.1   ,   2277.949 ,   2093.746 ,  16406.    ,
         7488.561 ,   7538.048 ,   4279.064 ,  17206.    ,   8698.764 ,
       152285.3   ,   4668.09  ,   1987.197 ,  13975.159 ,  15595.89  ,
         2631.71  ,  12171.    ,   4645.894 ,  11648.    ,  11814.116 ,
        14558.98  ,   2032.389 ,   5135.692 ])

In [21]:

import os
# Q9: Fix outlier prices


df = pd.read_csv(file_path)

# Normalize column names
df.columns = df.columns.str.strip().str.lower().str.replace('₹', '').str.replace(' ', '_')

# IQR bounds for fallback correction
Q1 = df['original_price_inr'].quantile(0.25)
Q3 = df['original_price_inr'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

# Define expected price ranges by subcategory
subcategory_price_ranges = {
    'smartphones': (5000, 100000),
    'smart_watch': (500, 15000),
    'audio': (300, 20000),
    'tablets': (5000, 60000),
    'laptops': (20000, 150000),
    'tv_&_entertainment': (10000, 150000)
}

# Correction logic using subcategory
def correct_price(row):
    price = row['original_price_inr']
    subcat = str(row.get('subcategory', '')).strip().lower().replace(' ', '_')
    expected = subcategory_price_ranges.get(subcat)
    
    if expected:
        min_p, max_p = expected
        if price > max_p * 10:
            return price / 100
        elif price < min_p / 10:
            return price * 100
    if price > upper_bound:
        return price / 100
    return price

# Apply correction
df['original_price_inr'] = df.apply(correct_price, axis=1)

# Save updated file
df.to_csv(file_path, index=False)
print("✅ Outlier prices corrected and saved for amazon_india_2024.csv")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\3271668278.py:5: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Outlier prices corrected and saved for amazon_india_2024.csv

##10 payment_method

In [22]:
df['payment_method'].unique()

<StringArray>
['Cash on Delivery', 'Debit Card', 'Credit Card', 'Net Banking']
Length: 4, dtype: str

In [23]:
import os
import pandas as pd
import numpy as np


df = pd.read_csv(file_path)

# Define mapping dictionary for payment methods
payment_mapping = {
    'upi': 'UPI',
    'phonepe': 'UPI',
    'googlepay': 'UPI',
    'bhim': 'UPI',

    'credit card': 'Credit Card',
    'creditcard': 'Credit Card',
    'cc': 'Credit Card',
    'visa': 'Credit Card',
    'mastercard': 'Credit Card',
    'BNPL' : 'Credit Card',

    'cash on delivery': 'Cash on Delivery',
    'cod': 'Cash on Delivery',
    'c.o.d': 'Cash on Delivery',
    'cash': 'Cash on Delivery',

    'debit card': 'Debit Card',
    'dc': 'Debit Card',
    'debitcard': 'Debit Card',

    'net banking': 'Net Banking',
    'netbanking': 'Net Banking',
    'nb': 'Net Banking',

    'emi': 'EMI',
    'installment': 'EMI',

    'wallet': 'Wallet',
    'paytm': 'Wallet',
    'amazonpay': 'Wallet',
    'mobikwik': 'Wallet'
}

# Function to clean payment method
def clean_payment_method(value):
    if pd.isna(value):
        return 'Unknown'
    value = str(value).lower().strip()
    # Check for exact key match first for a cleaner search in case of full strings
    if value in payment_mapping: 
        return payment_mapping[value]
    # Check for substring match (as in the original logic for cases like 'visa' in 'paid by visa cc')
    for key in payment_mapping:
        if key in value:
            return payment_mapping[key]
    return 'Other'

# Apply cleaning function
# Assuming the original column name is 'payment_method'
# If the column name is different, adjust 'payment_method' accordingly
df['payment_method'] = df['payment_method'].apply(clean_payment_method)

# Save the updated DataFrame back to the same file path string
df.to_csv(file_path, index=False)

print("✅ Payment method column cleaned and file updated successfully.")

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\814702657.py:6: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Payment method column cleaned and file updated successfully.

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33000 entries, 0 to 32999
Data columns (total 34 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   transaction_id          33000 non-null  str
 1   order_date              33000 non-null  str
 2   customer_id             33000 non-null  str
 3   product_id              33000 non-null  str
 4   product_name            33000 non-null  str
 5   category                33000 non-null  str
 6   subcategory             33000 non-null  str
 7   brand                   33000 non-null  str
 8   original_price_inr      33000 non-null  float64
 9   discount_percent        33000 non-null  float64
 10  discounted_price_inr    33000 non-null  float64
 11  quantity                33000 non-null  int64
 12  subtotal_inr            33000 non-null  float64
 13  delivery_charges        33000 non-null  int64
 14  final_amount_inr        33000 non-null  float64
 15  customer_city           32861 non-null  str
 16  customer_state          33000 non-null  str
 17  customer_tier           33000 non-null  str
 18  customer_spending_tier  33000 non-null  str
 19  customer_age_group      33000 non-null  str
 20  payment_method          33000 non-null  str
 21  delivery_days           33000 non-null  int64
 22  delivery_type           33000 non-null  str
 23  is_prime_member         33000 non-null  bool
 24  is_festival_sale        33000 non-null  bool
 25  festival_name           10541 non-null  str
 26  customer_rating         33000 non-null  float64
 27  return_status           33000 non-null  str
 28  order_month             33000 non-null  int64
 29  order_year              33000 non-null  int64
 30  order_quarter           33000 non-null  int64
 31  product_weight_kg       33000 non-null  float64
 32  is_prime_eligible       33000 non-null  bool
 33  product_rating          33000 non-null  float64
dtypes: bool(3), float64(8), int64(6), str(17)
memory usage: 7.9 MB

In [25]:
df.isnull().sum()

transaction_id                0
order_date                    0
customer_id                   0
product_id                    0
product_name                  0
category                      0
subcategory                   0
brand                         0
original_price_inr            0
discount_percent              0
discounted_price_inr          0
quantity                      0
subtotal_inr                  0
delivery_charges              0
final_amount_inr              0
customer_city               139
customer_state                0
customer_tier                 0
customer_spending_tier        0
customer_age_group            0
payment_method                0
delivery_days                 0
delivery_type                 0
is_prime_member               0
is_festival_sale              0
festival_name             22459
customer_rating               0
return_status                 0
order_month                   0
order_year                    0
order_quarter                 0
product_weight_kg             0
is_prime_eligible             0
product_rating                0
dtype: int64

In [26]:
df['delivery_charges'].unique()

array([0])

In [27]:
###ndelivery_charges null value remove

df = pd.read_csv(file_path)

# The correct way to replace the special NaN (Not a Number) value with 0
df['delivery_charges'] = df['delivery_charges'].fillna(0)
df['delivery_charges'] = df['delivery_charges'].astype(int)

df.to_csv(file_path, index=False)

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\3287117921.py:3: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [28]:
df['delivery_charges'].unique()

array([0])

In [29]:
df['customer_age_group'].unique()

<StringArray>
['46-55', '26-35', '36-45', '18-25', 'unknown', '55+']
Length: 6, dtype: str

In [30]:
df['customer_age_group']=df['customer_age_group'].fillna('unknown')
df.to_csv(file_path, index=False)

In [31]:
df['customer_city'].unique()

<StringArray>
[       'Mumbai',     'Allahabad',       'Kolkata',      'Ludhiana',
         'Delhi',       'Lucknow',        'Jaipur',   'Bhubaneswar',
     'Ahmedabad',     'Bengaluru',          'Pune',         'Kochi',
       'Chennai',        'Nagpur', 'Visakhapatnam',     'Gorakhpur',
        'Kanpur',    'Chandigarh',     'Hyderabad',       'Aligarh',
        'Indore',         'Patna',        'Meerut',    'Coimbatore',
      'Vadodara',    'Saharanpur',             nan,     'Moradabad',
         'Surat',      'Varanasi']
Length: 30, dtype: str

In [32]:
df = pd.read_csv(file_path)

# The correct way to replace the special NaN (Not a Number) value with 0
df['customer_city'] = df['customer_city'].fillna('unknown')

df.to_csv(file_path, index=False)

C:\Users\rishi\AppData\Local\Temp\ipykernel_25228\1464423568.py:1: DtypeWarning: Columns (0: festival_name) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [33]:
df.head()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2015_00000001,2015-01-25,CUST_2015_00003884,PROD_000021,Samsung Galaxy S6 16GB Black,Electronics,Smartphones,Samsung,123614.29,27.91,...,True,Republic Day Sale,5.0,Delivered,1,2015,1,0.19,True,4.7
1,TXN_2015_00000002,2015-01-05,CUST_2015_00011709,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.5,Delivered,1,2015,1,0.20,True,4.1
2,TXN_2015_00000003,2015-01-24,CUST_2015_00004782,PROD_000039,Samsung Galaxy Note 5 64GB Black,Electronics,Smartphones,Samsung,97644.25,46.93,...,True,Republic Day Sale,4.0,Delivered,1,2015,1,0.17,True,3.3
3,TXN_2015_00000004,2015-01-28,CUST_2015_00008105,PROD_000085,Motorola Moto G (3rd Gen) 16GB Black,Electronics,Smartphones,Motorola,21947.26,0.00,...,False,NaN,3.0,Delivered,1,2015,1,0.22,True,3.5
4,TXN_2015_00000005,2015-01-31,CUST_2015_00002955,PROD_000055,OnePlus OnePlus 2 16GB White,Electronics,Smartphones,OnePlus,54731.86,0.00,...,False,NaN,4.0,Delivered,1,2015,1,0.20,True,4.1

In [34]:
df['festival_name'].unique()

<StringArray>
[           'Republic Day Sale',                            nan,
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [35]:
df['festival_name'] = df['festival_name'].str.replace('', '', regex=False)
#df.to_csv(file_path, index=False)

In [36]:
df['festival_name'].unique()

<StringArray>
[           'Republic Day Sale',                            nan,
               'Valentine Sale',                'Holi Festival',
                  'Summer Sale',               'Back to School',
                    'Prime Day', 'Amazon Great Indian Festival',
                  'Diwali Sale']
Length: 9, dtype: str

In [37]:
df['customer_rating'].unique()

array([5. , 4.5, 4. , 3. , 3.5])

In [38]:
df['customer_rating'].describe()

count    33000.000000
mean         4.224788
std          0.502216
min          3.000000
25%          4.000000
50%          4.000000
75%          4.500000
max          5.000000
Name: customer_rating, dtype: float64

In [39]:
#df['customer_rating']=df['customer_rating'].fillna().mean
# Correct and concise one-line solution
#df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].25%())

df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].quantile(0.25))

df['customer_rating'] = df['customer_rating'].astype(float)

df.to_csv(file_path, index=False)

In [40]:
df['customer_rating'].unique()

array([5. , 4.5, 4. , 3. , 3.5])